export const defaultDataMap = [
  ["Region", "R$"],
  ["Acre", 0],
  ["Alagoas", 0],
  ["Amapá", 0],
  ["Amazonas", 0],
  ["Bahia", 0],
  ["Ceará", 0],
  ["Distrito Federal", 0],
  ["Espírito Santo", 0],
  ["Goiás", 0],
  ["Maranhão", 0],
  ["Mato Grosso", 0],
  ["Mato Grosso do Sul", 0],
  ["Minas Gerais", 0],
  ["Pará", 0],
  ["Paraíba", 0],
  ["Paraná", 0],
  ["Pernambuco", 0],
  ["Piauí", 0],
  ["Rio de Janeiro", 0],
  ["Rio Grande do Norte", 0],
  ["Rio Grande do Sul", 0],
  ["Rondônia", 0],
  ["Roraima", 0],
  ["Santa Catarina", 0],
  ["São Paulo", 0],
  ["Sergipe", 0],
  ["Tocantins", 0],
];